Controllers/CoursesController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Win32.SafeHandles;
using MileStone_Attendance_Management.Data;
using MileStone_Attendance_Management.Models;
using OfficeOpenXml;
using Newtonsoft.Json;
using System.Formats.Asn1;
using NuGet.Versioning;
using System.Globalization;
using CsvHelper;
using CsvHelper.Configuration;

namespace MileStone_Attendance_Management.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        
        public CoursesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
              return _context.Courses != null ? 
                          View(await _context.Courses.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
        }


        // GET: Courses/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var courses = await _context.Courses
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return _context.Courses != null ?
                          View(_context.Courses.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseId,CourseType,CourseName")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                try
                {   
                    _context.Add(courses);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    return Problem(e.Message);
                }
            }
            return _context.Courses != null ?
                          View(_context.Courses.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            ViewBag.Id = id;
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var courses = await _context.Courses.FindAsync(id);
            if (courses == null)
            {
                return NotFound();
            }
            return _context.Courses != null ?
                          View(await _context.Courses.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CourseId,CourseType,CourseName")] Courses courses)
        {
            if (id != courses.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(courses);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoursesExists(courses.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return _context.Courses != null ?
                          View(await _context.Courses.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
        }

        
        public async Task<IActionResult> Delete(string id)
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
            }
            var courses = await _context.Courses.FindAsync(id);
            if (courses != null)
            {
                _context.Courses.Remove(courses);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DeleteAll()
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Courses'  is null.");
            }

            try 
            {
                var courses = _context.Courses != null ?
                               _context.Courses.ToList() :
                              new List<Courses>();
                if (courses != null)
                {
                    foreach (var item in courses)
                    {
                        _context.Courses.Remove(item);
                        _context.SaveChanges();
                    }
                    return RedirectToAction(nameof(Index));
                }

            }
            catch(DBConcurrencyException ex)
            {
                return Problem(ex.Message);

            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
            return RedirectToAction(nameof(Index));
            
        } 
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(IFormFile UploadedFile)
        {
            if (Request != null)
            {
                if (Request.Form.Files.Count != 0 && !string.IsNullOrEmpty(UploadedFile.FileName))
                {

                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Files\", UploadedFile.FileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        UploadedFile.CopyTo(stream);
                    }
                    var csvConfig = new CsvConfiguration(CultureInfo.CurrentCulture)
                    {
                        HasHeaderRecord = false
                    };
                    using var streamReader = System.IO.File.OpenText(filePath);
                    using var csvReader = new CsvReader(streamReader, csvConfig);
                    List<Courses> courseList=new List<Courses>();
                    bool _firstEntryLoop = true;
                    while (csvReader.Read())
                    {
                        if (_firstEntryLoop)
                        {
                            try 
                            { 
                                _firstEntryLoop = false;
                                var course = new Courses();
                                course.CourseId = csvReader.GetField<string>(0);
                                course.CourseType = csvReader.GetField<string>(1);
                                course.CourseName = csvReader.GetField<string>(2);
                                if (course.CourseId == "CourseId" && course.CourseType == "CourseType" && course.CourseName == "CourseName")
                                {
                                    continue;
                                }
                                else
                                {
                                    return Problem("Incorrect Format of Fields Try Again");
                                }
                            }
                            catch(Exception ex) 
                            {
                                Problem(ex.Message);
                            }
                        }
                        else 
                        { 
                            var course = new Courses();
                            course.CourseId = csvReader.GetField<string>(0);
                            course.CourseType = csvReader.GetField<string>(1);
                            course.CourseName = csvReader.GetField<string>(2);
                            courseList.Add(course);
                        }
                    }
                    try
                    { 
                        foreach (var course in courseList)
                        {
                            _context.Add(course);
                        }
                    await _context.SaveChangesAsync();
                    }
                    catch(Exception e)
                    {
                        return Problem(e.Message);
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
                return RedirectToAction(nameof(Index), "Home");

Controllers/DegreesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MileStone_Attendance_Management.Data;
using MileStone_Attendance_Management.Models;

namespace MileStone_Attendance_Management.Controllers
{
    [Authorize(Roles ="Admin")]
    public class DegreesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public DegreesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Degrees
        public async Task<IActionResult> Index()
        {
              return _context.Degrees != null ? 
                          View(await _context.Degrees.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // GET: Degrees/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Degrees == null)
            {
                return NotFound();
            }

            var degrees = await _context.Degrees
                .FirstOrDefaultAsync(m => m.NormalizedDegree == id);
            if (degrees == null)
            {
                return NotFound();
            }

            return View(degrees);
        }

        // GET: Degrees/Create
        public IActionResult Create()
        {
            return _context.Degrees != null ?
                          View(_context.Degrees.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // POST: Degrees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Degree,NormalizedDegree")] Degrees degrees)
        {
            //if (ModelState.IsValid)
            try
            {
                _context.Add(degrees);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                    Problem(e.Message);
            }
            return _context.Degrees != null ?
                          View(_context.Degrees.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // GET: Degrees/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            ViewBag.Id= id;
            if (id == null || _context.Degrees == null)
            {
                return NotFound();
            }

            var degrees = await _context.Degrees.FindAsync(id);
            if (degrees == null)
            {
                return NotFound();
            }
            return _context.Degrees != null ?
                          View(await _context.Degrees.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // POST: Degrees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string Degree)
        {
            var degrees = await _context.Degrees.FindAsync(id);
            if (degrees == null)
            {
                return NotFound();
            }
            degrees.Degree = Degree;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(degrees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DegreesExists(degrees.NormalizedDegree))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(degrees);
        }

      
        public async Task<IActionResult> Delete(string id)
        {
            if (_context.Degrees == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
            }
            var degrees = await _context.Degrees.FindAsync(id);
            if (degrees != null)
            {
                _context.Degrees.Remove(degrees);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DegreesExists(string id)
        {
          return (_context.Degrees?.Any(e => e.NormalizedDegree == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MileStone Attendance Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MileStone_Attendance_Management.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3 " >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>MileStone Attendance Management</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Degrees" asp-action="Index">Degrees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SectionsAssigned" asp-action="Index">Sections</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="Index">Attendance</a>
                            </li>
                        }
                        else if (User.IsInRole("Attender"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CoursesAssignedGeneral" asp-action="Index">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AttenderSectionsAssigned" asp-action="Index">Sections</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="Index">Attendance</a>
                            </li>
                        }
                        else if (User.IsInRole("Professor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CoursesAssignedGeneral" asp-action="Index">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="Index">Attendance</a>
                            </li>
                        }
                        else if (User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CoursesAssignedGeneral" asp-action="Index">Courses</a>
                            </li><li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="StudentAttendance">Attendance</a>
                            </li>
                        } 
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CoursesAssignedGeneral" asp-action="Index">Courses</a>
                            </li>
                        }
                    </ul>
                    <partial  name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    @if (User.IsInRole("Admin")||User.IsInRole("Attender")||User.IsInRole("Professor")||User.IsInRole("Student"))
    {
    <div class="container" style="min-height:489px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        </div>
    }
    else
    {
        <div class="container" style="min-height:511px">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }
    <footer class="border-top footer text-dark bg-warning">
        <div class="container">
            &copy; 2023 - MileStone_Attendance_Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>