Controllers/CoursesAssignedController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using CsvHelper.Configuration;
using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MileStone_Attendance_Management.Data;
using MileStone_Attendance_Management.Models;
using System.Data;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace MileStone_Attendance_Management.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CoursesAssignedController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CoursesAssignedController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: CoursesAssigned
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CoursesAssigned.Include(c => c.Courses).Include(c => c.Degrees);
            return View(await applicationDbContext.ToListAsync());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(IFormFile UploadedFile)
        {
            if (Request != null)
            {
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Files\", UploadedFile.FileName);
                if(System.IO.File.Exists(filePath))
                {
                    
                    return Problem("This File is already Added Try another file to avoid duplicates");
                }
                if (Request.Form.Files.Count != 0 && !string.IsNullOrEmpty(UploadedFile.FileName))
                {
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        UploadedFile.CopyTo(stream);
                    }
                    var csvConfig = new CsvConfiguration(CultureInfo.CurrentCulture)
                    {
                        HasHeaderRecord = false
                    };
                    using var streamReader = System.IO.File.OpenText(filePath);
                    using var csvReader = new CsvReader(streamReader, csvConfig);
                    List<CoursesAssigned> courseList = new List<CoursesAssigned>();
                    bool _firstEntryLoop = true;
                    while (csvReader.Read())
                    {
                        if (_firstEntryLoop)
                        {
                            try { 
                                _firstEntryLoop = false;
                                var course = new CoursesAssigned();
                                course.CourseId = csvReader.GetField<string>(0);
                                course.NormalizedDegree = csvReader.GetField<string>(4);
                                course.NormalizedBranch = csvReader.GetField<string>(5);
                                if (course.CourseId == "CourseId"  && course.NormalizedDegree == "NormalizedDegree"&&course.NormalizedBranch == "NormalizedBranch")
                                {
                                    continue;
                                }
                                else
                                {
                                    streamReader.Close();
                                    System.IO.File.Delete(filePath);
                                    return Problem("Incorrect Format of Fields Try Again");
                                }
                            }
                            catch(Exception ex)
                            {
                                return Problem(ex.Message);

                            }
                        }
                        else
                        {
                            var course = new CoursesAssigned();
                            course.CourseId = csvReader.GetField<string>(0);
                            course.Semester = Convert.ToInt32(csvReader.GetField<string>(3));
                            course.NormalizedDegree = csvReader.GetField<string>(4);
                            course.NormalizedBranch = csvReader.GetField<string>(5);
                            courseList.Add(course);
                        }
                    }
                    try
                    {
                        foreach (var course in courseList)
                        {
                            _context.Add(course);
                        }
                        await _context.SaveChangesAsync();
                    }
                    catch (Exception e)
                    {
                        streamReader.Close();
                        System.IO.File.Delete(filePath);
                        return Problem("Forien Key error Check the courses, Degrees and Branches"+e.Message);
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            return RedirectToAction(nameof(Index), "Home");
        }

        // GET: CoursesAssigned/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CoursesAssigned == null)
            {
                return NotFound();
            }

            var coursesAssigned = await _context.CoursesAssigned
                .Include(c => c.Courses)
                .Include(c => c.Degrees)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coursesAssigned == null)
            {
                return NotFound();
            }

            return View(coursesAssigned);
        }

        // GET: CoursesAssigned/Create
        public IActionResult Create()
        {
            
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId");
            ViewData["CourseIds"] = _context.Courses.ToList();
            Dictionary<string, Courses> _coursesList = new Dictionary<string, Courses>();
            foreach (var c in _context.Courses.ToList())
            {
                _coursesList.Add(c.CourseId,c);
            }
            ViewBag.Courses = _coursesList;
            List<string> BranchNdDegree = new List<string>();
            Dictionary<string,List<int>> _durationList= new Dictionary<string,List<int>>();
            foreach(var item in _context.Branches.ToList())
            {
                BranchNdDegree.Add($"{item.NormalizedDegree}$@{item.NormalizedBranch}");
                if(!_durationList.ContainsKey($"{item.NormalizedDegree}$@{item.NormalizedBranch}"))
                {
                    List<int> _duration = new List<int>();
                    for(int i=1;i<=2*item.Duration;i++)
                    {
                        _duration.Add(i);
                    }
                    _durationList.Add($"{item.NormalizedDegree}$@{item.NormalizedBranch}",_duration);
                }
            }
            ViewBag.Duration= _durationList;
            ViewData["BranchNdDegree"] = BranchNdDegree.Distinct().ToList();    


            return View();
        }

        // POST: CoursesAssigned/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            CoursesAssigned coursesAssigned=new CoursesAssigned();
            ViewData["CourseIds"] = _context.Courses.ToList();
            List<string> BranchNdDegree = new List<string>();
            foreach (var item in _context.Branches.ToList())
            {
                BranchNdDegree.Add($"{item.NormalizedDegree}$@{item.NormalizedBranch}");
            }
            ViewData["BranchNdDegree"] = BranchNdDegree.Distinct().ToList();
            Dictionary<string, List<int>> _durationList = new Dictionary<string, List<int>>();
            foreach (var item in _context.Branches.ToList())
            {
                BranchNdDegree.Add($"{item.NormalizedDegree}$@{item.NormalizedBranch}");
                if (!_durationList.ContainsKey($"{item.NormalizedDegree}$@{item.NormalizedBranch}"))
                {
                    List<int> _duration = new List<int>();
                    for (int i = 1; i <= 2 * item.Duration; i++)
                    {
                        _duration.Add(i);
                    }
                    _durationList.Add($"{item.NormalizedDegree}$@{item.NormalizedBranch}", _duration);
                }
            }
            ViewBag.Duration = _durationList;
            Dictionary<string, Courses> _coursesList = new Dictionary<string, Courses>();
            foreach (var c in _context.Courses.ToList())
            {
                _coursesList.Add(c.CourseId, c);
            }
            ViewBag.Courses = _coursesList;
            var _strings= collection["SelectedBranchNdDegree"].ToString().Split("$@");
            coursesAssigned.NormalizedDegree = _strings[0];
            coursesAssigned.NormalizedBranch = _strings[1];
            coursesAssigned.CourseId = collection["SelectedCourseId"].ToString();
            coursesAssigned.Semester = Convert.ToInt32(collection["Semester"].ToString());
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(coursesAssigned);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception e)
                {
                    Problem(e.Message);
                }
            }

Views/Courses/Create.cshtml
@model IEnumerable<MileStone_Attendance_Management.Models.Courses>

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Courses</h4>
<table class="table">
    <thead>
        <tr>
            <th width="150px">
                @Html.DisplayNameFor(model => model.CourseId)
            </th>
            <th width="150px">
                @Html.DisplayNameFor(model => model.CourseType)
            </th>
            <th >
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <form asp-action="Create" method="post">
            <td>
                <input name="CourseId" class="form-control" placeholder="@Html.DisplayNameFor(model => model.CourseId)" />
            </td>
            <td>
                <input name="CourseType" class="form-control" placeholder="@Html.DisplayNameFor(model => model.CourseType)" />
            </td>
            <td>
                <input name="CourseName" class="form-control" placeholder="@Html.DisplayNameFor(model => model.CourseName)" />
            </td>
            <td>
                <button type="submit" class="btn btn-success">Apply</button> |
                <a asp-action="Index" class="btn btn-warning">Cancel</a>
            </td>
            </form>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseName)
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.CourseId">Edit</a> |
                    <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.CourseId">Details</a> |
                    <button asp-action="Delete" class="btn btn-danger" asp-route-id="@item.CourseId" onclick='myDeleteCourse("/Courses/Delete/@item.CourseId","@item.CourseName")'>Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Courses/Details.cshtml
@model MileStone_Attendance_Management.Models.Courses

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div>
    <h4>Courses</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model?.CourseId">Edit</a> |
    <a asp-action="Index" class="btn btn-warning">Back to List</a>
</div>

Views/Courses/Edit.cshtml
@model IEnumerable<MileStone_Attendance_Management.Models.Courses>

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<h4>Courses</h4>
<table class="table">
    <thead>
        <tr>
            <th width="150px">
                @Html.DisplayNameFor(model => model.CourseId)
            </th>
            <th width="150px">
                @Html.DisplayNameFor(model => model.CourseType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.CourseId == ViewBag.Id)
            {
                <tr>
                    <form asp-action="Edit" method="post">
                        <td>
                            <input name="CourseId" class="form-control" value="@item.CourseId" readonly placeholder="@Html.DisplayNameFor(model => model.CourseId)" />
                        </td>
                        <td>
                            <input name="CourseType" class="form-control" value="@item.CourseType" placeholder="@Html.DisplayNameFor(model => model.CourseType)" />
                        </td>
                        <td>
                            <input name="CourseName" class="form-control" value="@item.CourseName" placeholder="@Html.DisplayNameFor(model => model.CourseName)" />
                        </td>
                        <td>
                            <button type="submit" class="btn btn-success">Apply</button> |
                            <a asp-action="Index" class="btn btn-warning">Cancel</a>
                        </td>
                    </form>
                </tr>
            }
            else
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourseId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourseType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourseName)
                    </td>
                    <td>
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.CourseId">Edit</a> |
                        <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.CourseId">Details</a> |
                        <button asp-action="Delete" class="btn btn-danger" asp-route-id="@item.CourseId" onclick='myDeleteCourse("/Courses/Delete/@item.CourseId","@item.CourseName")'>Delete</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Courses/Index.cshtml
@model IEnumerable<MileStone_Attendance_Management.Models.Courses>

@{
    ViewData["Title"] = "Courses";
}

<div class="float-parent-element">
    <div class="float-child-element1">
        <div class="red"> 
            <h1>Courses
                <a asp-action="Index" asp-controller="CoursesAssigned" class="btn btn-sm btn-dark">Assign Courses</a>
            </h1>
        </div>
    </div>
    <div class="float-child-element2">
        <div class="yellow">
            
            <form id="UploadedFileForm" method="post" enctype="multipart/form-data">
                <p align="right">
                    <a asp-action="Index" class="btn btn-primary">&#8634;</a>
                    <label for="UploadedFile">
                        <a for="UploadedFile" class="btn btn-success">+ Add Via File(.csv)</a>
                    </label>
                    <input id="UploadedFile" name="UploadedFile" onchange="document.getElementById('UploadedFileForm').submit()" type="file" accept="text/csv" hidden />
                    <a asp-action="Create" class="btn btn-success">+ Create New</a>
                    <button asp-action="DeleteAll" class="btn btn-danger" onclick='myDeleteAll("/Courses/DeleteAll","Courses")'>Delete All</button>

                </p>
            </form>
            
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.CourseId">Edit</a> |
                <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.CourseId">Details</a> |
                <button asp-action="Delete" class="btn btn-danger" asp-route-id="@item.CourseId" onclick='myDeleteCourse("/Courses/Delete/@item.CourseId","@item.CourseName")'>Delete</button>
            </td>
        </tr>
    }
    </tbody>
</table>
<style>
    .float-parent-element {
        width: 100%;
    }

    .float-child-element1 {
        float: left;
        width: 50%;
    }

    .float-child-element2 {
        float: right;
        width: 50%;
        padding: 15px 0px;
    }
</style>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}