Models/Degrees.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MileStone_Attendance_Management.Models
{
    [Index(nameof(Degree), IsUnique = true)]
    public class Degrees
    {
        [Display(Name = "Degree Name")]
        [Required(ErrorMessage = "Degree Name is Required")]
        public string Degree { get; set; }
        [Key]
        [Display(Name = "Normalized Degree")]
        [Required(ErrorMessage = "Normalized Degree Name is Required")]
        public string NormalizedDegree { get; set; }
    }
}

Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MileStone_Attendance_Management.Data;
using MileStone_Attendance_Management.Models;

namespace MileStone_Attendance_Management.Controllers
{
    [Authorize(Roles ="Admin")]
    public class BranchesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public BranchesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Branches
        public async Task<IActionResult> Index()
        {
              return _context.Branches != null ? 
                          View(await _context.Branches.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Branches'  is null.");
        }

        // GET: Branches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Branches == null)
            {
                return NotFound();
            }

            var branches = await _context.Branches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branches == null)
            {
                return NotFound();
            }

            return View(branches);
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            ViewBag.DegreeList = _context.Degrees != null ?
                          _context.Degrees.ToList() : new List<Degrees>();
            return _context.Branches != null ?
                          View(_context.Branches.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Branches'  is null.");
        }

        // POST: Branches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Branch,NormalizedBranch,NormalizedDegree,Duration")] Branches branches)
        {
            
            var degree = _context.Degrees.Find(branches.NormalizedDegree);
            branches.Degree = degree.Degree;
            //if (ModelState.IsValid)
            
                try
                {
                    _context.Add(branches);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Error: {e.Message}");
                }
            
            return _context.Branches != null ?
                          View(_context.Branches.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Branches'  is null.");
        }

        // GET: Branches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Id = id;
            ViewBag.DegreeList = _context.Degrees != null ?
                          _context.Degrees.ToList() : new List<Degrees>();
            if (id == null || _context.Branches == null)
            {
                return NotFound();
            }

            var branches = await _context.Branches.FindAsync(id);
            if (branches == null)
            {
                return NotFound();
            }
            return _context.Branches != null ?
                          View(await _context.Branches.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Branches'  is null.");
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormCollection collection)
        {
            Branches branches=new Branches();
            branches.Id = id;
            if (id != branches.Id)
            {
                return NotFound();
            }
            var degree = _context.Degrees.Find(collection["NormalizedDegree"]);
            branches.Degree = degree.Degree;
            branches.Branch = collection["Branch"];
            branches.NormalizedDegree = collection["NormalizedDegree"];
            branches.NormalizedBranch = collection["NormalizedBranch"];
            branches.Duration = Convert.ToInt32(collection["Duration"]);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branches);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchesExists(branches.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branches);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Branches == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Branches'  is null.");
            }
            var branches = await _context.Branches.FindAsync(id);
            if (branches != null)
            {
                _context.Branches.Remove(branches);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BranchesExists(int id)
        {
          return (_context.Branches?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/DegreesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MileStone_Attendance_Management.Data;
using MileStone_Attendance_Management.Models;

namespace MileStone_Attendance_Management.Controllers
{
    [Authorize(Roles ="Admin")]
    public class DegreesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public DegreesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Degrees
        public async Task<IActionResult> Index()
        {
              return _context.Degrees != null ? 
                          View(await _context.Degrees.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // GET: Degrees/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Degrees == null)
            {
                return NotFound();
            }

            var degrees = await _context.Degrees
                .FirstOrDefaultAsync(m => m.NormalizedDegree == id);
            if (degrees == null)
            {
                return NotFound();
            }

            return View(degrees);
        }

        // GET: Degrees/Create
        public IActionResult Create()
        {
            return _context.Degrees != null ?
                          View(_context.Degrees.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // POST: Degrees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Degree,NormalizedDegree")] Degrees degrees)
        {
            //if (ModelState.IsValid)
            try
            {
                _context.Add(degrees);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                    Problem(e.Message);
            }
            return _context.Degrees != null ?
                          View(_context.Degrees.ToList()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // GET: Degrees/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            ViewBag.Id= id;
            if (id == null || _context.Degrees == null)
            {
                return NotFound();
            }

            var degrees = await _context.Degrees.FindAsync(id);
            if (degrees == null)
            {
                return NotFound();
            }
            return _context.Degrees != null ?
                          View(await _context.Degrees.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
        }

        // POST: Degrees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string Degree)
        {
            var degrees = await _context.Degrees.FindAsync(id);
            if (degrees == null)
            {
                return NotFound();
            }
            degrees.Degree = Degree;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(degrees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DegreesExists(degrees.NormalizedDegree))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(degrees);
        }

      
        public async Task<IActionResult> Delete(string id)
        {
            if (_context.Degrees == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Degrees'  is null.");
            }
            var degrees = await _context.Degrees.FindAsync(id);
            if (degrees != null)
            {
                _context.Degrees.Remove(degrees);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DegreesExists(string id)
        {
          return (_context.Degrees?.Any(e => e.NormalizedDegree == id)).GetValueOrDefault();
        }
    }
}

Views/Degrees/Create.cshtml
@model IEnumerable<MileStone_Attendance_Management.Models.Degrees>

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Degrees</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NormalizedDegree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <form asp-action="Create" method="post">
            <td>
                <input name="NormalizedDegree" class="form-control" placeholder="@Html.DisplayNameFor(model => model.NormalizedDegree)" />
            </td>
            <td>
                <input name="Degree"  class="form-control" placeholder="@Html.DisplayNameFor(model => model.Degree)" />
            </td>
            <td>
                <button type="submit" class="btn btn-success">Apply</button> |
                <a asp-action="Index" class="btn btn-warning">Cancel</a>
            </td>
        </form>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NormalizedDegree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Degree)
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.NormalizedDegree">Edit</a> |
                    <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.NormalizedDegree">Details</a> |
                    <button asp-action="Delete" class="btn btn-danger" asp-route-id="@item.NormalizedDegree" onclick='myDeleteDegree("/Degrees/Delete/@item.NormalizedDegree","@item.Degree")'>Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Degrees/Details.cshtml
@model MileStone_Attendance_Management.Models.Degrees

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Degrees</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NormalizedDegree)
        </dt>
       <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NormalizedDegree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model?.NormalizedDegree">Edit</a> |
    <a asp-action="Index" class="btn btn-warning">Back to List</a>
</div>

Views/Degrees/Edit.cshtml
@model IEnumerable<MileStone_Attendance_Management.Models.Degrees>

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<h4>Degrees</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NormalizedDegree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if(item.NormalizedDegree==ViewBag.Id)
            {
                <tr>
                    <form asp-action="Edit" asp-route-id="@item.NormalizedDegree" method="post">
                        <td>
                            @Html.DisplayFor(modelItem => item.NormalizedDegree)
                        </td>
                        <td>
                        <input name="Degree" class="form-control" value="@item.Degree" placeholder="@Html.DisplayNameFor(model => model.Degree)" />
                        </td>
                        <td>
                            <button type="submit" class="btn btn-success">Apply</button> |
                            <a asp-action="Index" class="btn btn-warning">Cancel</a>
                        </td>
                    </form>
                </tr>
            }
            else{
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NormalizedDegree)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Degree)
                    </td>
                    <td>
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.NormalizedDegree">Edit</a> |
                        <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.NormalizedDegree">Details</a> |
                        <button asp-action="Delete" class="btn btn-danger" asp-route-id="@item.NormalizedDegree" onclick='myDeleteDegree("/Degrees/Delete/@item.NormalizedDegree","@item.Degree")'>Delete</button>

                    </td>
                </tr>
            }
        }
        
    </tbody>
</table>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Degrees/Index.cshtml
@model IEnumerable<MileStone_Attendance_Management.Models.Degrees>

@{
    ViewData["Title"] = "Degrees";
}
<div class="float-parent-element">
    <div class="float-child-element1">
        <div class="red">
            <h1>Degrees <a asp-action="Index" asp-controller="Branches" class="btn btn-sm btn-dark">Branches</a></h1>
        </div>
    </div>
    <div class="float-child-element2">
        <div class="yellow">
            <p align="right">
                <a asp-action="Index" class="btn btn-primary">&#8634;</a>
                <a asp-action="Create" class="btn btn-success">+ Create New</a>
            </p>
        </div>
    </div>
</div>


        
    

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NormalizedDegree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NormalizedDegree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Degree)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.NormalizedDegree">Edit</a> |
                <a asp-action="Details" class="btn btn-warning"  asp-route-id="@item.NormalizedDegree">Details</a> |
                <button asp-action="Delete" class="btn btn-danger" asp-route-id="@item.NormalizedDegree" onclick='myDeleteDegree("/Degrees/Delete/@item.NormalizedDegree","@item.Degree")'>Delete</button>

            </td>
        </tr>
}
    </tbody>
</table>
<style>
    .float-parent-element {
        width: 100%;
    }

    .float-child-element1 {
        float: left;
        width: 50%;
    }.float-child-element2 {
        float: right;
        width: 50%;
        padding:15px 0px;
    }
</style>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}